# RK3588 kernel Image with bundled initramfs (~110MB) is much larger than typical ARM
# kernels. image-balena mirrors the entire FAT boot partition into rootfs at /resin-boot/,
# so that ~110MB Image (in BALENA_BOOT_PARTITION_FILES) is added to the rootfs on top of
# the base ~265MB. The hostapp/inactive image (do_image_hostapp_ext4) is truncated to
# exactly ROOTFS_SIZE and then populated with `mkfs.ext4 -d`; since we pin SIZE == MAXSIZE,
# ROOTFS_SIZE cannot grow past it. At 512MB the populated content + ext4 journal/inode/
# reserved overhead overflowed while copying "Image". Use 768MB for headroom.
# (rootA + rootB each grow by 256MB — negligible on the 128GB eMMC target.)
IMAGE_ROOTFS_SIZE = "786432"
IMAGE_ROOTFS_MAXSIZE = "786432"

# Use GPT (same as meta-balena-rockpi RK3399 setup).
PARTITION_TABLE_TYPE = "gpt"

# Reserve 40MB before the first data partition. This leaves room for the ~9.7MB U-Boot
# blob (sectors 64..19064) in the gap before the FAT boot partition (sector 81920).
DEVICE_SPECIFIC_SPACE = "40960"

# Two reserved partitions at the front keep the balena partition numbering stable:
# resin-boot = p3, resin-rootA = p4, matching `root=/dev/mmcblk0p4` in extlinux.conf.
# They also mark the bootloader region as allocated. The single binman U-Boot blob
# (see IMAGE_CMD:append below) is dd'd across sectors 64..19064, which sits inside
# this reserved region (loader2 ends at 24575, resin-boot starts at sector 81920).
device_specific_configuration:rockchip-rk3588-rock-5t() {
    parted -s ${BALENA_RAW_IMG} unit s mkpart loader1 64 8063
    parted -s ${BALENA_RAW_IMG} unit s mkpart loader2 16384 24575
}

# Remove any stale .balenaos-img from prior builds before parted assembles a new one.
# parted prompts interactively when it finds an existing partition table on the file,
# breaking unattended incremental rebuilds. Prepend the deletion so it runs first.
IMAGE_CMD:balenaos-img:prepend:rockchip-rk3588-rock-5t () {
    rm -f ${BALENA_RAW_IMG}
}

# Write U-Boot to raw sectors after the image is assembled. u-boot-rockchip.bin is the
# binman single blob from the u-boot-rock5t recipe (mainline v2025.04): IDB/SPL header at
# offset 0 + U-Boot FIT (incl. BL31/ATF) at its correct internal offset, so one dd at
# sector 64 covers pre-loader + U-Boot proper. The image already depends on
# virtual/bootloader:do_deploy (UBOOT_MACHINE is set), so the blob is deployed first.
#
# This replaces the radxa 2017.09 split (idblock.img @64 + uboot.img @16384), whose SPL
# had to scan the GPT and gunzip uboot.img — on balena's 128-entry GPT it exhausted its
# malloc pool ("alloc_read_gpt_entries: Can't allocate ... Invalid GPT") and never reached
# U-Boot proper. The binman blob avoids both: no GPT scan, no gunzip.
IMAGE_CMD:balenaos-img:append:rockchip-rk3588-rock-5t () {
    dd if=${DEPLOY_DIR_IMAGE}/u-boot-rockchip.bin of=${BALENA_RAW_IMG} conv=notrunc bs=512 seek=64
}

# extlinux.conf + extra_uEnv.txt (in BALENA_BOOT_PARTITION_FILES) are produced by the
# u-boot-rock5t do_deploy. meta-balena only makes do_resin_boot_dirgen_and_deploy depend on
# grub-conf, not on the u-boot bootloader, so add the dependency explicitly — otherwise this
# task races the from-source U-Boot build and fails with "extra_uEnv.txt is an invalid path".
do_resin_boot_dirgen_and_deploy[depends] += "${@' virtual/bootloader:do_deploy' if d.getVar('MACHINE') == 'rockchip-rk3588-rock-5t' else ''}"

# do_image_size_check looks for BALENA_DOCKER_IMG in IMGDEPLOYDIR, which is not
# populated when do_image_docker is sstate-restored. Skip the check — rootfs is
# manually sized at 512MB (IMAGE_ROOTFS_SIZE) against 128GB eMMC target.
python do_image_size_check() {
    bb.note("do_image_size_check skipped for %s (rootfs manually sized)" % d.getVar("MACHINE"))
}

# RK3588 kernel with bundled initramfs (Image-initramfs) is large: ~62MB kernel +
# ~48MB initramfs. U-Boot only has FAT support, so it must live in resin-boot.
# hup_sanity_check requires: data + largest_file + fat_overhead <= boot_size, i.e.
# roughly 2x the bundled image + overhead. ~110MB image => ~220MB + FAT overhead.
# Use 256MB. (Default BALENA_BOOT_SIZE is 40MB — far too small.)
BALENA_BOOT_SIZE:rockchip-rk3588-rock-5t = "262144"

# Kernel (with initramfs), DTB, and extlinux.conf go into the FAT resin-boot partition.
# extlinux.conf is generated by u-boot-rockchip.bbappend do_deploy:append.
# U-Boot's distro_bootcmd scans the bootable FAT partition for /extlinux/extlinux.conf.
BALENA_BOOT_PARTITION_FILES:append:rockchip-rk3588-rock-5t = " \
    Image-initramfs-rockchip-rk3588-rock-5t.bin:/Image-initramfs-rockchip-rk3588-rock-5t.bin \
    rk3588-rock-5t.dtb:/rk3588-rock-5t.dtb \
    extlinux/extlinux.conf:/extlinux/extlinux.conf \
"

# Modem (Quectel EM05-G/EC25-G), NIC (RTL8125B), and WiFi (RTL8852BE) support.
# Modem modules stay available for USB hotplug. r8169-late-load defers PCIe NIC probing
# until userspace. WiFi (RTL8852BE) is the in-tree rtw89 driver in the armbian rkr5.1
# kernel, so it autoloads via PCI alias — no out-of-tree recipe or delayed-load service.
IMAGE_INSTALL:append:rockchip-rk3588-rock-5t = " \
    kernel-module-usbserial \
    kernel-module-usb-wwan \
    kernel-module-option \
    kernel-module-cdc-wdm \
    kernel-module-qmi-wwan \
    linux-firmware-rtw89 \
    linux-firmware-rtl8125b \
    wireless-regdb-static \
    r8169-late-load \
"
